# Generated by Django 5.2.15 on 2026-07-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_mobile', models.IntegerField()),
                ('user_reg_date', models.DateField(auto_now_add=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'user_registration',
            },
        ),
    ]
