# Generated by Django 5.2.15 on 2026-07-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0002_alter_userregistration_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
