# Generated by Django 5.2.15 on 2026-07-13 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0003_alter_userregistration_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
