# Generated by Django 5.2.15 on 2026-07-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0004_alter_userregistration_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
