# Generated by Django 5.2.15 on 2026-07-14 03:36

import UserReg.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0005_alter_userregistration_user_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_name',
            field=models.CharField(max_length=30, validators=[UserReg.validators.name_filed_validator]),
        ),
    ]
