# Generated by Django 5.2.15 on 2026-07-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('user_reg_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(default='Male', max_length=10)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
